---
- include_tasks: check-existence.yml

- name: Create webroot directory if it doesn't exist yet
  file:
    path: "{{ cert_item.webroot | default(certbot_webroot) }}"
    state: directory

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not cert_exists
