---
- name: Ensure snapd is installed.
  package:
    name: snapd
    state: present
  register: snapd_install

- name: Ensure snapd is enabled.
  systemd:
    name: snapd.socket
    enabled: true
    state: started

- name: Enable classic snap support.
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: ansible_os_family != "Debian"

- name: Update snap after install.
  shell: snap install core; snap refresh core
  changed_when: true
  failed_when: false
  when: snapd_install is changed

- name: Install certbot via snap.
  snap:
    name: certbot
    classic: true

- name: Symlink certbot into place.
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  ignore_errors: "{{ ansible_check_mode }}"

- name: Make sure certbot Trust Plugins With Root is set.
  command: snap set certbot trust-plugin-with-root=ok
  when:
    - certbot_dns_plugin is defined

- name: Install DNS Plugin - {{ certbot_dns_plugin }}.
  snap:
    name: "certbot-dns-{{ certbot_dns_plugin }}"
    classic: true
  when: certbot_dns_plugin is defined

- name: Install Nginx Plugin.
  package:
    name: "python3-certbot-nginx"
    state: present
  when: certbot_nginx is defined

- name: Set Certbot script variable.
  set_fact:
    certbot_script: /usr/bin/certbot
